### PR TITLE
Additional testing of the ast module.

### PR DESCRIPTION
**Pull request by git-harry**

### CODE REVIEW

**Comment by git-harry** [comment]
retest

**Comment by git-harry** [comment]
retest

**Comment by git-harry** [comment]
retest

**Comment by git-harry** [comment]
retest

**Comment by galstrom21** [comment]
retest

**Comment by willkelly** [comment]
What about now!?

**Comment by willkelly** [comment]
retest

**Comment by galstrom21** [comment]
the last error is a legit pep8 violation

**Pull request merged**
